### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [KazDragon/telnetpp#194]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by KazDragon** [comment]
This is a really, really good idea and given that I am a proud owner of a JFrog puzzle cube, I thought I should at least give it a go.  However, building my Boost dependency causes internal compiler errors on Travis, and the proposed workaround is to use docker containers.  I will put this back into the Ready state until I have time to work on that.
