### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by volundmush** [KazDragon/telnetpp#206]
Hey! I'm looking to create a new MUD server (at the moment just for teaching myself C++, but hey, who knows where it'll go?) I found out about Conan thanks to your library here, which I intend to use. ... Unfortunately telnetpp doesn't seem to be available on conan-central and I have no idea how to add it to my [requires] for conanfile.txt...?

Might be great to add a little how-to to your README.md. I've got NO idea how to grab this and use conan install.

I think it would be hella easy to make a modern MUD server using conan's package manager to grab Poco, telnetpp, and whatever else... just code up the game logic and BAM. :dancing_men:

**Comment by volundmush** [comment]
I think I figured out the series of steps required. Took me some hunting and I happened to get lucky. conan seems pretty cool but it doesn't make it very obvious where to find repositories and how to get them going:

```
conan remote add kazdragon https://api.bintray.com/conan/kazdragon/conan-public
conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
conan remote add martinmoene https://api.bintray.com/conan/martinmoene/nonstd-lite
```

And then the specific package for either conan install or [requires] is:
```
telnetpp/2.0.0@kazdragon/conan-public
```

However, now I'm getting this error:

```
telnetpp/2.0.0@kazdragon/conan-public: WARN: Can't find a 'telnetpp/2.0.0@kazdragon/conan-public' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=gcc, compiler.libcxx=libstdc++, compiler.version=8, os=Linux
- Options: coverage=False, sanitize=off, shared=False, withTests=False, withZlib=True, boost_container:shared=False, boost_exception:shared=False, zlib:fPIC=True, zlib:minizip=False, zlib:shared=False
- Dependencies: boost_container/1.69.0@bincrafters/stable, boost_exception/1.69.0@bincrafters/stable, boost_signals2/1.69.0@bincrafters/stable, boost_variant/1.69.0@bincrafters/stable, gsl-lite/0.34.0@nonstd-lite/stable, zlib/1.2.11@conan/stable
- Package ID: 0137555e692f9ffa25c24bbe1d533385fee90504

ERROR: Missing prebuilt package for 'telnetpp/2.0.0@kazdragon/conan-public'
Try to build it from sources with "--build telnetpp"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
```

Not sure if this is important or not.

**Comment by volundmush** [comment]
I'm coming closer and closer to figuring out how both conan and C++ compiling and linking in general works! But now I'm running into a new problem...

I'm getting this when I do:
```
conan install .. --build telnetpp
```

https://i.imgur.com/tKHr0rM.png

I have gsl-lite installed, though the version if 0.34.0. 0.26 doesn't seem to be available. Is telnetpp not compatible with the latest version or am I doing something wrong?

**Comment by KazDragon** [comment]
You're not doing anything wrong.  My reference conan package is by agauniyal and he hasn't moved on that I can see since 0.26.  Fortunately, Martin Moene has set up his own repo (https://bintray.com/martinmoene/nonstd-lite/gsl-lite%3Anonstd-lite/0.34.0%3Astable), so it's hopefully just a configuration issue.

**Comment by KazDragon** [comment]
Also, I never managed to work out how to reliably update a pre-built package, so I always do a conan install with "--build=missing" and it just figures it out.

**Comment by KazDragon** [comment]
For viewers reading this issue to discover how to install: I still have yet to write the documentation properly.  However, https://github.com/KazDragon/rot13server is a small project that demonstrates Telnet++ and it does have instructions on how to build, including the Conan repositories, etc.

**Comment by KazDragon** [comment]
After careful consideration, I have decided to import my rot13server project as an example to Telnet++.  It includes the exact command lines that are used to set up the Conan remotes, perform the Conan installation and to build the project.

I could probably wax more lyrical in the documentation, but I can't think of a better way of demonstrating the project than a small, self-contained example.
