### ISSUE TITLE
should be noted boost requsites

### ISSUE THREAD

**Issue by alexrayne** [KazDragon/telnetpp#212]
imho, in project description, and read.me better be noted, that project need boost

**Comment by KazDragon** [comment]
I could do add that and, in fact, it used to be there.  However, I changed the project a while ago to manage its requirements using Conan, which means that it sorts out its dependencies itself.  So I'm not sure what would be gained by adding this information up front.

Is there a decision that a louder statement of dependencies would enable you to make?

**Comment by alexrayne** [comment]
i`ve spent couple of hours on sources, while stop at boost header dependance. yes, some people avoids boost.
If you remove such dependance, or note that it is not critical for library usage, imho, project could be mo apropriatable

**Comment by KazDragon** [comment]
Boost requisites are explicitly noted since #218.  I have no plans to remove them.
