### ISSUE TITLE
conan gives ERROR: Unable to find 'serverpp/0.0.5@kazdragon/conan-public' in remotes

### ISSUE THREAD

**Issue by bevinhex** [KazDragon/telnetpp#243]
Hi, I was about to try out the library, here are steps I took
`cd /tmp`
`git clone https://github.com/KazDragon/telnetpp.git`
`cd telnetpp/examples`
`conan install . --build missing`
then I get following
```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

serverpp/0.0.5@kazdragon/conan-public: Not found in local cache, looking in remotes...
serverpp/0.0.5@kazdragon/conan-public: Trying with 'conan-center'...
ERROR: Unable to find 'serverpp/0.0.5@kazdragon/conan-public' in remotes

```
I also tried to search for the package in conan center, cannot find anything related

**Comment by KazDragon** [comment]
Hi Bevinhex, and a hearty thank you for your interest in my work.

serverpp is my own library, and a very shallow wrapper around some basic Boost.Asio networking.  It's at github.com/KazDragon/telnetpp.git.  It is available via Conan, and I put the instructions for that on the readme for the rot13server example.  In short, you have to add my bintray space as a remote:

`conan remote add kazdragon-conan https://api.bintray.com/conan/kazdragon/conan-public`

Telnetpp is also in that bintray space -- at least until the end of the month, when it shuts down; I hope to have an alternative by then -- if you want to use it in your own projects.

**Comment by bevinhex** [comment]
Thanks for the quick response, alright, now able to find the repository , completely missed that README inside example, perhaps it is good idea to include `conan remote add kazdragon-conan https://api.bintray.com/conan/kazdragon/conan-public` line on homepage as well.
 
inside `examples/rot13server` gives another error now
```
WARN: serverpp/0.0.5@kazdragon/conan-public: requirement boost/[>=1.69] overridden by your conanfile to boost/1.75.0 
ERROR: Version range '>=1.69' from requirement 'boost_container/[>=1.69]@bincrafters/stable' required by 'telnetpp/2.0.1@kazdragon/conan-public' could not be resolved in local cache
```
I believe I have boost/1.75.0 cached , and it's been fine for other library linkage so far on all platforms (linux/windows(mingw)/android/macos/ios), but not sure if those options inside `conanfile.txt` has anything to do with it:
```
[options]
boost:without_fiber=True
boost:without_stacktrace=True
boost:without_log=True
boost:without_locale=True
boost:without_test=True
```
not quite sure how conan takes dependencies, since those are for another project, didn't touch example conanfile though.

**Comment by KazDragon** [comment]
Ah, I believe that I have failed to update the version number in the rot13server example.  If you change the version of telnetpp in conanfile.txt from 2.0.1 to 2.2.0, I think that should help.

**Comment by bevinhex** [comment]
That got it working , thanks

**Comment by KazDragon** [comment]
Thanks for the feedback.  I'll update that in the repo.
