### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by CalielOfSeptem** [KazDragon/telnetpp#251]
Not a bug.  Just a thanks for releasing this as a separate project.  Years ago I used your telnet code that was embedded within a different project of yours.  I was making my own mud in C++ with a custom lua parser.  My dream is to reproduce LP-mud-esque functionality but with the elegance and simplicity of lua.   Your telnet code worked great.

Covid and other life events put the mud project on hold- but now I am back.  I was very pleased to see that you released the telnet code in its own project!  Thank you for the hard work and making it freely available.

**Comment by KazDragon** [comment]
Hi @CalielOfSeptem.  I remember it well.  It was a very exciting time.  Users!  

I'm still around doing the occasional maintenance in case there's anything you discover or need.
